# .goreleaser.yml
project_name: particlelifesim
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
      - 386
    id: "particlelifesim"
    dir: .
    main: ./cmd/particlelifesim
